const fs = require('fs');
let c = fs.readFileSync('src/components/CMSDashboard.tsx', 'utf8');

c = c.replace(
  "                      <div className=\"flex justify-between items-center border-b border-editorial-border pb-2 mb-4\">\n                        <h4 className=\"font-serif text-lg text-editorial-navy\">{selectedMessage.type}</h4>",
  "                      <div className=\"flex justify-between items-center border-b border-editorial-border pb-2 mb-4\">\n                        <div className=\"flex items-center gap-3\">\n                          <h4 className=\"font-serif text-lg text-editorial-navy\">{selectedMessage.type}</h4>\n                          <select\n                            value={selectedMessage.status || 'Pending'}\n                            onChange={async (e) => {\n                              const newStatus = e.target.value as 'Pending' | 'In Progress' | 'Completed';\n                              const updatedMsg = { ...selectedMessage, status: newStatus };\n                              try {\n                                await saveDocument('messages', updatedMsg.id, updatedMsg);\n                                setSelectedMessage(updatedMsg);\n                                setMessages(messages.map(m => m.id === updatedMsg.id ? updatedMsg : m));\n                              } catch (err) {\n                                console.error('Error updating status', err);\n                                alert('Failed to update status.');\n                              }\n                            }}\n                            className={`text-[10px] font-mono uppercase tracking-widest font-bold px-2 py-1 border rounded-none cursor-pointer focus:outline-none focus:ring-1 focus:ring-editorial-navy ${\n                              selectedMessage.status === 'Completed' ? 'bg-emerald-50 text-emerald-700 border-emerald-200' : \n                              selectedMessage.status === 'In Progress' ? 'bg-amber-50 text-amber-700 border-amber-200' :\n                              'bg-rose-50 text-rose-700 border-rose-200'\n                            }`}\n                          >\n                            <option value=\"Pending\">Pending</option>\n                            <option value=\"In Progress\">In Progress</option>\n                            <option value=\"Completed\">Completed</option>\n                          </select>\n                        </div>"
);

fs.writeFileSync('src/components/CMSDashboard.tsx', c);
